spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/turbo-az-copy
    username: postgres
    password: 
  jpa:
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: smtp = true
          starttls:
            enable: true


server:
  port: 8008
